//! Turning damlc's rendered script result into Markdown.
//!
//! The transaction view is already a monospaced tree separated by `<br>`, so it
//! survives as a fenced code block almost unchanged. The table view is a real
//! HTML table and becomes a Markdown one. Nothing here needs a general HTML
//! parser: the markup is machine-generated by damlc and small.

/// Renders the whole document. `source` is shown so the reader can tell which
/// script the pane is currently showing.
pub fn render(html: &str, title: &str, source: &str) -> String {
    let mut out = format!("# {title}\n\n`{source}`\n");

    if let Some(note) = element(html, "div", "note").map(|n| text_of(&n)) {
        let note = note.trim();
        if !note.is_empty() {
            out.push_str(&format!("\n> {note}\n"));
        }
    }

    match element(html, "div", "da-code") {
        Some(transactions) => {
            let body = text_of(&transactions);
            out.push_str("\n## Transactions\n\n```\n");
            out.push_str(body.trim_matches('\n'));
            out.push_str("\n```\n");
        }
        None => out.push_str("\n_No transaction view in this result._\n"),
    }

    let tables = tables_of(html);
    if !tables.is_empty() {
        out.push_str("\n## Contracts\n");
        for table in &tables {
            out.push_str(&format!("\n### {}\n\n", table.caption));
            out.push_str(&table.to_markdown());
        }
        out.push_str(
            "\nS = signatory, O = observer, W = witness, D = divulged, `-` = not disclosed\n",
        );
    }

    out
}

pub struct Table {
    pub caption: String,
    pub header: Vec<String>,
    pub rows: Vec<Vec<String>>,
}

impl Table {
    fn to_markdown(&self) -> String {
        let mut out = String::new();
        out.push_str(&format!("| {} |\n", self.header.join(" | ")));
        out.push_str(&format!("|{}|\n", vec!["---"; self.header.len()].join("|")));
        for row in &self.rows {
            out.push_str(&format!("| {} |\n", row.join(" | ")));
        }
        out
    }
}

/// Every `<table>` in the document, captioned by the `<h1>` that precedes it -
/// damlc emits one per template.
fn tables_of(html: &str) -> Vec<Table> {
    let mut tables = Vec::new();
    let mut rest = html;
    while let Some(start) = rest.find("<table") {
        let caption = rest[..start]
            .rfind("<h1>")
            .map(|h| {
                let after = &rest[h + 4..start];
                text_of(&after[..after.find("</h1>").unwrap_or(after.len())])
                    .trim()
                    .to_string()
            })
            .unwrap_or_default();
        let Some(end) = rest[start..].find("</table>") else {
            break;
        };
        let body = &rest[start..start + end];
        let mut rows = rows_of(body);
        if !rows.is_empty() {
            let header = rows.remove(0);
            tables.push(Table {
                caption,
                header,
                rows,
            });
        }
        rest = &rest[start + end + "</table>".len()..];
    }
    tables
}

fn rows_of(table: &str) -> Vec<Vec<String>> {
    let mut rows = Vec::new();
    let mut rest = table;
    while let Some(start) = rest.find("<tr") {
        let Some(end) = rest[start..].find("</tr>") else {
            break;
        };
        let row = &rest[start..start + end];
        let cells: Vec<String> = cells_of(row);
        if !cells.is_empty() {
            rows.push(cells);
        }
        rest = &rest[start + end + "</tr>".len()..];
    }
    rows
}

fn cells_of(row: &str) -> Vec<String> {
    let mut cells = Vec::new();
    let mut rest = row;
    loop {
        let th = rest.find("<th");
        let td = rest.find("<td");
        let (start, close) = match (th, td) {
            (Some(a), Some(b)) if a < b => (a, "</th>"),
            (Some(a), None) => (a, "</th>"),
            (_, Some(b)) => (b, "</td>"),
            (None, None) => break,
        };
        let Some(end) = rest[start..].find(close) else {
            break;
        };
        let inner = &rest[start..start + end];
        let inner = &inner[inner.find('>').map(|i| i + 1).unwrap_or(0)..];
        // A cell can be empty, and an empty Markdown cell is still a cell.
        cells.push(escape_cell(text_of(inner).trim()));
        rest = &rest[start + end + close.len()..];
    }
    cells
}

/// A pipe would end the Markdown cell early; a newline would end the row.
fn escape_cell(text: &str) -> String {
    text.replace('|', "\\|").replace('\n', " ")
}

/// The contents of the first element with this tag and class, without the
/// element's own tags.
fn element(html: &str, tag: &str, class: &str) -> Option<String> {
    let open = format!("<{tag}");
    let close = format!("</{tag}>");
    let mut from = 0;
    while let Some(rel) = html[from..].find(&open) {
        let start = from + rel;
        let head_end = html[start..].find('>')? + start;
        let head = &html[start..head_end];
        if !head.contains(class) {
            from = head_end;
            continue;
        }
        // Balance nesting, so an inner div does not end the search early.
        let mut depth = 1usize;
        let mut cursor = head_end + 1;
        while depth > 0 {
            let next_open = html[cursor..].find(&open).map(|i| cursor + i);
            let next_close = html[cursor..].find(&close).map(|i| cursor + i);
            match (next_open, next_close) {
                (Some(o), Some(c)) if o < c => {
                    depth += 1;
                    cursor = o + open.len();
                }
                (_, Some(c)) => {
                    depth -= 1;
                    if depth == 0 {
                        return Some(html[head_end + 1..c].to_string());
                    }
                    cursor = c + close.len();
                }
                _ => return Some(html[head_end + 1..].to_string()),
            }
        }
    }
    None
}

/// Tags out, `<br>` to newlines, entities decoded. Tooltip text is dropped: it
/// is a hover explanation that would otherwise be glued onto the letter it
/// explains, turning `S` into `SSignatory`.
fn text_of(html: &str) -> String {
    let bytes = html.as_bytes();
    let mut out = String::with_capacity(html.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'<' {
            let Some(rel) = html[i..].find('>') else {
                break;
            };
            let tag = &html[i..i + rel + 1];
            if tag.starts_with("<br") {
                out.push('\n');
            } else if tag.contains("tooltiptext") {
                // Skip the element wholesale, not just its tag.
                let after = i + rel + 1;
                match html[after..].find("</span>") {
                    Some(end) => {
                        i = after + end + "</span>".len();
                        continue;
                    }
                    None => break,
                }
            }
            i += rel + 1;
            continue;
        }
        if bytes[i] == b'&' {
            if let Some(rel) = html[i..].find(';') {
                if rel <= 8 {
                    out.push_str(&unescape(&html[i..i + rel + 1]));
                    i += rel + 1;
                    continue;
                }
            }
        }
        let ch = html[i..].chars().next().expect("a char boundary");
        out.push(ch);
        i += ch.len_utf8();
    }
    out
}

fn unescape(entity: &str) -> String {
    match entity {
        "&amp;" => "&".to_string(),
        "&lt;" => "<".to_string(),
        "&gt;" => ">".to_string(),
        "&quot;" => "\"".to_string(),
        "&#39;" | "&apos;" => "'".to_string(),
        "&nbsp;" => " ".to_string(),
        other => other
            .strip_prefix("&#")
            .and_then(|n| n.trim_end_matches(';').parse::<u32>().ok())
            .and_then(char::from_u32)
            .map(String::from)
            .unwrap_or_else(|| other.to_string()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Captured from a real damlc render by scripts/probe-protocol.py.
    const FIXTURE: &str = include_str!("../tests/fixtures/script-result.html");

    #[test]
    fn decodes_entities_and_line_breaks() {
        assert_eq!(text_of("a<br>b"), "a\nb");
        assert_eq!(text_of("&#39;Alice&#39;"), "'Alice'");
        assert_eq!(text_of("&quot;TV&quot; &amp; more"), "\"TV\" & more");
    }

    #[test]
    fn drops_tooltip_text_so_a_letter_stays_a_letter() {
        let cell = r#"<div class="tooltip"><span>S</span><span class="tooltiptext">Signatory</span></div>"#;
        assert_eq!(text_of(cell).trim(), "S");
    }

    #[test]
    fn finds_a_nested_element_without_ending_early() {
        let html = r#"<div class="outer">a<div class="inner">b</div>c</div>tail"#;
        assert_eq!(
            element(html, "div", "outer").unwrap(),
            r#"a<div class="inner">b</div>c"#
        );
    }

    #[test]
    fn renders_the_transaction_tree_verbatim() {
        let out = render(FIXTURE, "Script: setup", "test/daml/Test.daml");
        assert!(out.contains("## Transactions"));
        assert!(out.contains("TX 0 1970-01-01T00:00:00Z"));
        assert!(out.contains("└─> 'Alice' creates Main:Asset"));
        assert!(out.contains("issuer = 'Alice'; owner = 'Alice'; name = \"TV\""));
        assert!(out.contains("Return value:"));
    }

    #[test]
    fn renders_the_contract_table() {
        let out = render(FIXTURE, "Script: setup", "test/daml/Test.daml");
        assert!(out.contains("## Contracts"));
        assert!(out.contains("| id | status | issuer | owner | name |"));
        assert!(out.contains("| #2:1 | active | 'Alice' | 'Alice' | \"TV\" |"));
        // The disclosure letters must not have their tooltips glued on.
        assert!(!out.contains("SSignatory"));
    }

    #[test]
    fn captions_each_table_with_its_template() {
        let out = render(FIXTURE, "Script: setup", "test/daml/Test.daml");
        assert!(out.contains("### Main:Asset@"));
    }

    #[test]
    fn puts_the_title_and_source_first() {
        let out = render(FIXTURE, "Script: setup", "test/daml/Test.daml");
        assert!(out.starts_with("# Script: setup\n\n`test/daml/Test.daml`\n"));
    }

    #[test]
    fn a_cell_containing_a_pipe_does_not_break_the_table() {
        let html = r#"<h1>T</h1><table><tr><th>a</th></tr><tr><td>x|y</td></tr></table>"#;
        let tables = tables_of(html);
        assert_eq!(tables[0].rows[0][0], "x\\|y");
    }

    #[test]
    fn survives_a_result_with_no_table() {
        let out = render(
            r#"<html><body><div class="da-code transaction">Transactions:<br>  none</div></body></html>"#,
            "Script: empty",
            "a.daml",
        );
        assert!(out.contains("Transactions:\n  none"));
        assert!(!out.contains("## Contracts"));
    }
}
